import moment from 'moment';

export const tableData = [
   {
      key: '1',
      title: '🚀 Lesson 1 - Intro to ML with TF',
      status: 'To-do',
      date: moment('05/31/2023').format('L'),
      tags: ['study', 'AI/ML'],
      type: 'Note',
   },
   {
      key: '2',
      title: '✨ Seminar Note',
      status: 'Done',
      date: moment('05/01/2023').format('L'),
      tags: ['CV'],
      type: 'Canvas',
   },
   {
      key: '3',
      title: '✌️ PyTorch Introduction',
      status: 'Review',
      date: moment('05/01/2023').format('L'),
      tags: ['PyTorch'],
      type: 'Canvas',
   },
   {
      key: '4',
      title: 'Head First Design Pattern.pdf',
      status: 'In progress',
      date: moment('05/01/2023').format('L'),
      tags: ['SWE', 'architecture'],
      type: 'File',
   },
   {
      key: '5',
      title: '👁️ Intro to Computer Vision',
      status: 'To-do',
      date: moment('05/01/2023').format('L'),
      tags: ['study', 'AI/ML'],
      type: 'Note',
   },
   {
      key: '6',
      title: '🌐 Intro to Convolution',
      status: 'To-do',
      date: moment('04/30/2023').format('L'),
      tags: ['study', 'AI/ML'],
      type: 'Note',
   },
   {
      key: '7',
      title: '🖼️ Working with complex images',
      status: 'Done',
      date: moment('04/30/2023').format('L'),
      tags: ['study', 'AI/ML'],
      type: 'Note',
   },
   {
      key: '8',
      title: '💪 Image Augmentation',
      status: 'To-do',
      date: moment('04/30/2023').format('L'),
      tags: ['study', 'CV'],
      type: 'Note',
   },
   {
      key: '9',
      title: '🔍 Multi Class Classification',
      status: 'Done',
      date: moment('04/30/2023').format('L'),
      tags: ['study', 'deep learning'],
      type: 'Canvas',
   },
   {
      key: '10',
      title: 'Hands on Machine Learning with Scikit Learn and Tensorflow',
      status: 'To-do',
      date: moment('04/30/2023').format('L'),
      tags: ['sklearn', 'tf'],
      type: 'File',
   },
]